sudo: required
services:
  - docker

before_install:
  - docker image build -t rgeddes/docker-react -f Dockerfile.dev .

script:
  - docker container run -e CI=true rgeddes/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-783688164403"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
